import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import picomatch from 'picomatch';

import { createConfig } from '@brandonramsey/eslint';
import policy from '@brandonramsey/eslint/plugins/policy';
import style from '@brandonramsey/eslint/plugins/style';

import type { OxlintConfig, OxlintOverride } from '@brandonramsey/eslint';

// Executed from .tooling/scripts after the strict tools build.
const root = fileURLToPath(new URL('../../', import.meta.url));
const outputArgument = process.argv.indexOf('--output');
const outputPath = outputArgument === -1 ? 'examples' : process.argv[outputArgument + 1];
assert.ok(outputPath !== undefined && outputPath.length > 0 && !outputPath.startsWith('--'), '--output requires a directory');
const output = resolve(root, outputPath);
const checking = process.argv.includes('--check');

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function record(value: unknown): Record<string, unknown> {
  assert.ok(isRecord(value));
  return value;
}

async function json(url: URL): Promise<unknown> {
  return JSON.parse(await readFile(url, 'utf8'));
}

const peerURL = new URL(import.meta.resolve('oxlint/package.json'));
const peer = record(await json(peerURL));
const manifest = record(await json(new URL('../../package.json', import.meta.url)));
const schema = record(await json(new URL('./configuration_schema.json', peerURL)));
// The pinned schema lists native owners; unqualified names belong to eslint.
const native = Object.keys(record(record(record(schema.definitions).DummyRuleMap).properties))
  .map((id) => id.includes('/') ? id : `eslint/${id}`);
const inventory = [...native, ...Object.keys(style.rules).map((id) => `style/${id}`), ...Object.keys(policy.rules).map((id) => `policy/${id}`)].sort();
assert.equal(new Set(inventory).size, inventory.length, 'Duplicate inventory identities');

const config = createConfig({ projectRoot: root, syntaxOnlyFiles: ['tools/**/*.{ts,cts}'] });
// All native presets are disabled by the public policy; unspecified entries are off.
assert.deepEqual(config.categories, { correctness: 'off' });
for (const rules of [config.rules, ...config.overrides?.map((override) => override.rules) ?? []]) {
  for (const id of Object.keys(rules ?? {})) {
    assert.ok(inventory.includes(id), `Configured rule missing from inventory: ${id}`);
  }
}

function completeRules(rules: OxlintConfig['rules']): NonNullable<OxlintConfig['rules']> {
  return Object.fromEntries(inventory.map((id) => [id, rules?.[id] ?? 'off']));
}

function sortedRules(rules: OxlintConfig['rules']): NonNullable<OxlintConfig['rules']> {
  return Object.fromEntries(Object.entries(rules ?? {}).sort(([left], [right]) => left.localeCompare(right, 'en')));
}

const ruleProfiles = (config.overrides ?? []).filter((override) => override.rules !== undefined);
assert.equal(ruleProfiles.length, 5, 'Review the editable example scaffold when public profile stages change');

const example = `// Generated by npm run references. Copy this file before editing.
// Save at your project root as oxlint.config.mjs and pass --config explicitly.
// Consumer paths, plugin loading and file selections come from the public factory.
import { createConfig } from '${String(manifest.name)}';

// Every available native and packaged bridge rule, including disabled rules.
const rules = ${JSON.stringify(completeRules(config.rules), null, 2)};

// Edit these profile entries for settings that override the base rules above.
const [syntax, typed, declarations, tests, syntaxOnly] = ${JSON.stringify(ruleProfiles.map((override) => sortedRules(override.rules)), null, 2)};

export function createExample(options = {}) {
  const base = createConfig(options);
  const policyCount = base.overrides.length - (options.overrides?.length ?? 0);
  const profiles = [syntax, typed, declarations, ...(options.tests === false ? [] : [tests]), syntaxOnly];
  let profile = 0;
  return {
    ...base,
    rules: structuredClone(rules),
    overrides: [
      ...base.overrides.slice(0, policyCount).map((override) => override.rules === undefined
        ? override
        : { ...override, rules: structuredClone(profiles[profile++]) }),
      ...base.overrides.slice(policyCount),
    ],
  };
}

// cwd is the default root. Pass factory options here for explicit selections:
// createExample({ projectRoot: import.meta.dirname, syntaxOnlyFiles: ['tools/**/*.ts'] })
export default createExample();
`;

const profiles = {
  'javascript-esm': 'src/source.mjs',
  'javascript-commonjs': 'src/source.cjs',
  'javascript-test-esm': 'src/source.test.mjs',
  'javascript-test-commonjs': 'src/source.test.cjs',
  'typescript-esm': 'src/source.mts',
  'typescript-commonjs': 'src/source.cts',
  'typescript-test-esm': 'src/source.test.mts',
  'typescript-test-commonjs': 'src/source.test.cts',
  'typescript-syntax-esm': 'tools/config.mts',
  'typescript-syntax-commonjs': 'tools/config.cts',
  'typescript-syntax-test-esm': 'tools/config.test.mts',
  'typescript-syntax-test-commonjs': 'tools/config.test.cts',
  'declarations-esm': 'src/ambient.d.mts',
  'declarations-commonjs': 'src/ambient.d.cts',
};

// Include mts as well as ts so dedicated extensions represent portable modes.
const referenceConfig = createConfig({ projectRoot: root, syntaxOnlyFiles: ['tools/**/*.{ts,mts,cts}'] });

function applies(override: OxlintOverride, file: string): boolean {
  return picomatch.isMatch(file, override.files)
    && !picomatch.isMatch(file, override.excludeFiles ?? []);
}

function resolvedProfile(file: string): OxlintConfig {
  const result: OxlintConfig = {
    rules: completeRules(referenceConfig.rules),
    globals: { ...referenceConfig.globals },
    env: { ...referenceConfig.env },
    plugins: referenceConfig.plugins,
    options: referenceConfig.options,
    // Root-dependent import settings are loaded by createConfig in the example.
    settings: Object.fromEntries(Object.entries(referenceConfig.settings ?? {}).filter(([name]) => name !== 'policy')),
  };
  for (const override of referenceConfig.overrides ?? []) {
    if (applies(override, file)) {
      Object.assign(result.rules ?? {}, override.rules);
      Object.assign(result.globals ?? {}, override.globals);
      Object.assign(result.env ?? {}, override.env);
    }
  }
  return result;
}

const outputs = new Map<string, string>([['complete-config.mjs', example]]);
const rows: string[] = [];
for (const [name, file] of Object.entries(profiles)) {
  const resolved = resolvedProfile(file);
  outputs.set(`rules/${name}.mjs`, `// Generated by npm run references; do not edit.
// Native Oxlint reference profile: ${name}. Representative file: ${file}.
// Configured settings only; rule-internal defaults are not expanded.
// Consumer-root import settings and plugin paths are supplied by complete-config.mjs.
export default ${JSON.stringify(resolved, null, 2)};
`);
  const enabled = Object.values(resolved.rules ?? {}).filter((setting) => (Array.isArray(setting) ? setting[0] : setting) === 'error').length;
  rows.push(`| [${name}](rules/${name}.mjs) | ${file} | ${String(enabled)} |`);
}

const dependencies = record(manifest.dependencies);
outputs.set('README.md', `# Native Oxlint rule reference

Copy [complete-config.mjs](complete-config.mjs) to your project root as \`oxlint.config.mjs\`, then run \`npx oxlint --config oxlint.config.mjs .\` from that root. The unedited example reproduces this package's defaults. It uses the public \`createConfig\` export to derive consumer paths, package-aware globals, bundled plugin loading and profile selections. No repository or fixture roots are embedded. The [basic example](basic-config.mjs) remains the shortest default setup.

Edit explicit entries in \`rules\` for base settings. Edit the named \`syntax\`, \`typed\`, \`declarations\`, \`tests\` or \`syntaxOnly\` maps where a profile overrides that setting. For example, change \`'style/semi'\` in \`rules\` to \`['error', 'never']\`; change typed promise options in \`typed\`. Root edits do not override later profile entries. Keep \`createConfig\` and the composition code to retain default plugin setup. Pass factory options to the final \`createExample\` call for explicit roots, \`syntaxOnlyFiles\`, \`testFiles\`, \`tests: false\`, resolver options or final consumer overrides; see [the public interface](../docs/oxlint-configuration.md). Each call clones settings so edits to one result do not leak into another.

Generated from Oxlint ${String(peer.version)}'s pinned schema and public packaged plugin exports (Stylistic ${String(dependencies['@stylistic/eslint-plugin'])}). Each of the ${String(Object.keys(profiles).length)} profiles lists all ${String(inventory.length)} available rules: ${String(native.length)} native identities across all native owners, ${String(Object.keys(style.rules).length)} style rules and ${String(Object.keys(policy.rules).length)} selected policy bridge rules. Rules from inactive native owners remain explicitly off; enabling one also requires adding its owner to \`plugins\`. Core rules use the explicit \`eslint/\` owner. Providers used privately by the bridge are not separately registered rule namespaces.

Reference profiles resolve ordered public rules, globals and environment overrides for representative files, with configured options intact. Omitted internal defaults are not expanded. Dedicated extensions represent ESM/CommonJS independently of the generation checkout. JSX uses JavaScript settings; TSX uses TypeScript settings. The example retains dynamic nearest-package settings for ambiguous extensions. The profile modules are reference snapshots, not standalone configurations; their root-dependent import settings and plugin specifiers come from the factory in the complete example.

| Profile | Representative file | Enabled rules |
| --- | --- | --- |
${rows.join('\n')}

Native Oxlint/tsgolint owns typed-project selection and inferred programs; no custom coverage warning or independent preflight is supplied. Declaration and explicit syntax-only selections disable configured typed rules. Disable-comment explanations are recommended but unenforced; unused-directive errors and blanket-disable rejection remain configured. Consumers own execution and repeated fixing. See [support boundaries](../docs/support.md).

Run \`npm run references\` to regenerate, then review and commit the example, profiles and this summary. \`npm run references:check\` strictly builds the TypeScript generator and fails for any stale or missing generated output, including the complete example and summary. Generation reads metadata and public configuration; it executes no lint engine or per-rule probes. Public tests verify example equivalence, profile settings, inventory and drift. The full development check is \`npm run check\`.
`);

await mkdir(resolve(output, 'rules'), { recursive: true });
const drift: string[] = [];
await Promise.all([...outputs].map(async ([path, contents]) => {
  const destination = resolve(output, path);
  if (checking) {
    const existing = await readFile(destination, 'utf8').catch(() => '');
    if (existing !== contents) {
      drift.push(path);
    }
  }
  else {
    await writeFile(destination, contents);
  }
}));
if (drift.length > 0) {
  throw new Error(`Reference drift: ${drift.sort().join(', ')}. Run npm run references and review the difference.`);
}
console.log(`${checking ? 'Verified' : 'Generated'} editable example and ${String(Object.keys(profiles).length)} profiles with ${String(inventory.length)} rules each.`);
