import type { OxlintConfig } from 'oxlint';

// Explicit policy from the validated candidate; no upstream presets.
export const baseRules = {
  'policy/no-dupe-args': 'error',
  'policy/no-octal': 'error',
  'policy/no-unresolved': [
    'error',
    {
      commonjs: true,
      caseSensitive: true,
    },
  ],
  'policy/no-useless-path-segments': 'error',
  'policy/no-extraneous-dependencies': [
    'error',
    {
      devDependencies: true,
    },
  ],
  'policy/order': [
    'error',
    {
      groups: [
        'builtin',
        'external',
        'internal',
        'parent',
        'sibling',
        'index',
        'object',
        'type',
      ],
      'newlines-between': 'always',
      alphabetize: {
        order: 'asc',
        caseInsensitive: true,
      },
      named: true,
      warnOnUnassignedImports: false,
    },
  ],
  'policy/no-deprecated-api': 'error',
  'policy/node-builtins': 'error',
  'policy/es-builtins': 'error',
  'policy/no-process-exit': 'error',
  'policy/prefer-node-protocol': 'error',
  'policy/no-unnecessary-polyfills': 'error',
  'eslint/constructor-super': 'error',
  'eslint/for-direction': 'error',
  'eslint/getter-return': 'error',
  'eslint/no-async-promise-executor': 'error',
  'eslint/no-await-in-loop': 'error',
  'eslint/no-case-declarations': 'error',
  'eslint/no-class-assign': 'error',
  'eslint/no-compare-neg-zero': 'error',
  'eslint/no-cond-assign': [
    'error',
    'always',
  ],
  'eslint/no-const-assign': 'error',
  'eslint/no-constant-binary-expression': 'error',
  'eslint/no-constant-condition': [
    'error',
    {
      checkLoops: 'allExceptWhileTrue',
    },
  ],
  'eslint/no-control-regex': 'error',
  'eslint/no-debugger': 'error',
  'eslint/no-delete-var': 'error',
  'eslint/no-dupe-class-members': 'error',
  'eslint/no-dupe-else-if': 'error',
  'eslint/no-dupe-keys': 'error',
  'eslint/no-duplicate-case': 'error',
  'eslint/no-empty': [
    'error',
    {
      allowEmptyCatch: false,
    },
  ],
  'eslint/no-empty-character-class': 'error',
  'eslint/no-empty-function': 'error',
  'eslint/no-empty-pattern': 'error',
  'eslint/no-empty-static-block': 'error',
  'eslint/no-eval': 'error',
  'eslint/no-ex-assign': 'error',
  'eslint/no-fallthrough': 'error',
  'eslint/no-global-assign': 'error',
  'eslint/no-implicit-coercion': 'error',
  'eslint/no-import-assign': 'error',
  'eslint/no-inner-declarations': [
    'error',
    'functions',
    {
      blockScopedFunctions: 'allow',
    },
  ],
  'eslint/no-invalid-regexp': 'error',
  'eslint/no-irregular-whitespace': 'error',
  'eslint/no-loss-of-precision': 'error',
  'eslint/no-misleading-character-class': 'error',
  'eslint/no-new-native-nonconstructor': 'error',
  'eslint/no-new-wrappers': 'error',
  'eslint/no-nonoctal-decimal-escape': 'error',
  'eslint/no-obj-calls': 'error',
  'eslint/no-promise-executor-return': 'error',
  'eslint/no-prototype-builtins': 'error',
  'eslint/no-redeclare': 'error',
  'eslint/no-regex-spaces': 'error',
  'eslint/no-self-assign': 'error',
  'eslint/no-self-compare': 'error',
  'eslint/no-setter-return': 'error',
  'eslint/no-shadow': 'error',
  'eslint/no-shadow-restricted-names': 'error',
  'eslint/no-sparse-arrays': 'error',
  'eslint/no-template-curly-in-string': 'error',
  'eslint/no-this-before-super': 'error',
  'eslint/no-throw-literal': 'error',
  'eslint/no-undef': 'error',
  'eslint/no-unexpected-multiline': 'error',
  'eslint/no-unreachable': 'error',
  'eslint/no-unreachable-loop': 'error',
  'eslint/no-unsafe-finally': 'error',
  'eslint/no-unsafe-negation': 'error',
  'eslint/no-unsafe-optional-chaining': [
    'error',
    {
      disallowArithmeticOperators: true,
    },
  ],
  'eslint/no-unused-expressions': 'error',
  'eslint/no-unused-labels': 'error',
  'eslint/no-unused-private-class-members': 'error',
  'eslint/no-unused-vars': [
    'error',
    {
      args: 'all',
      argsIgnorePattern: '^_',
      caughtErrors: 'all',
      caughtErrorsIgnorePattern: '^_',
      varsIgnorePattern: '^_',
      ignoreRestSiblings: true,
    },
  ],
  'eslint/no-use-before-define': [
    'error',
    {
      functions: false,
    },
  ],
  'eslint/no-useless-backreference': 'error',
  'eslint/no-useless-catch': 'error',
  'eslint/no-useless-escape': 'error',
  'eslint/no-var': 'error',
  'eslint/no-with': 'error',
  'eslint/object-shorthand': [
    'error',
    'always',
  ],
  'eslint/prefer-const': [
    'error',
    {
      destructuring: 'all',
    },
  ],
  'eslint/prefer-object-spread': 'error',
  'eslint/prefer-promise-reject-errors': 'error',
  'eslint/prefer-rest-params': 'error',
  'eslint/prefer-spread': 'error',
  'eslint/require-yield': 'error',
  'eslint/use-isnan': 'error',
  'eslint/valid-typeof': 'error',
  'eslint/curly': [
    'error',
    'all',
  ],
  'eslint/eqeqeq': [
    'error',
    'always',
  ],
  'eslint/complexity': [
    'error',
    {
      max: 10,
    },
  ],
  'eslint/max-depth': [
    'error',
    4,
  ],
  'eslint/max-params': [
    'error',
    {
      max: 4,
    },
  ],
  'style/array-bracket-spacing': [
    'error',
    'never',
  ],
  'style/arrow-parens': [
    'error',
    'always',
    {
      requireForBlockBody: true,
    },
  ],
  'style/arrow-spacing': [
    'error',
    {
      after: true,
      before: true,
    },
  ],
  'style/block-spacing': [
    'error',
    'always',
  ],
  'style/brace-style': [
    'error',
    'stroustrup',
    {
      allowSingleLine: true,
    },
  ],
  'style/comma-dangle': [
    'error',
    'always-multiline',
  ],
  'style/comma-spacing': [
    'error',
    {
      after: true,
      before: false,
    },
  ],
  'style/comma-style': [
    'error',
    'last',
  ],
  'style/computed-property-spacing': [
    'error',
    'never',
    {
      enforceForClassMembers: true,
    },
  ],
  'style/dot-location': [
    'error',
    'property',
  ],
  'style/eol-last': 'error',
  'style/generator-star-spacing': [
    'error',
    {
      after: true,
      before: false,
    },
  ],
  'style/indent': [
    'error',
    2,
    {
      ArrayExpression: 1,
      CallExpression: {
        arguments: 1,
      },
      flatTernaryExpressions: false,
      FunctionDeclaration: {
        body: 1,
        parameters: 1,
        returnType: 1,
      },
      FunctionExpression: {
        body: 1,
        parameters: 1,
        returnType: 1,
      },
      ignoreComments: false,
      ignoredNodes: [
        'TSUnionType',
        'TSIntersectionType',
      ],
      ImportDeclaration: 1,
      MemberExpression: 1,
      ObjectExpression: 1,
      offsetTernaryExpressions: true,
      outerIIFEBody: 1,
      SwitchCase: 1,
      tabLength: 2,
      VariableDeclarator: 1,
    },
  ],
  'style/indent-binary-ops': [
    'error',
    2,
  ],
  'style/key-spacing': [
    'error',
    {
      afterColon: true,
      beforeColon: false,
    },
  ],
  'style/keyword-spacing': [
    'error',
    {
      after: true,
      before: true,
    },
  ],
  'style/lines-between-class-members': [
    'error',
    'always',
    {
      exceptAfterSingleLine: true,
    },
  ],
  'style/max-statements-per-line': [
    'error',
    {
      max: 1,
    },
  ],
  'style/member-delimiter-style': [
    'error',
    {
      multiline: {
        delimiter: 'semi',
        requireLast: true,
      },
      multilineDetection: 'brackets',
      overrides: {
        interface: {
          multiline: {
            delimiter: 'semi',
            requireLast: true,
          },
        },
      },
      singleline: {
        delimiter: 'semi',
      },
    },
  ],
  'style/multiline-ternary': [
    'error',
    'always-multiline',
  ],
  'style/new-parens': 'error',
  'style/no-extra-parens': [
    'error',
    'functions',
  ],
  'style/no-floating-decimal': 'error',
  'style/no-mixed-operators': [
    'error',
    {
      allowSamePrecedence: true,
      groups: [
        [
          '==',
          '!=',
          '===',
          '!==',
          '>',
          '>=',
          '<',
          '<=',
        ],
        [
          '&&',
          '||',
        ],
        [
          'in',
          'instanceof',
        ],
      ],
    },
  ],
  'style/no-mixed-spaces-and-tabs': 'error',
  'style/no-multi-spaces': 'error',
  'style/no-multiple-empty-lines': [
    'error',
    {
      max: 1,
      maxBOF: 0,
      maxEOF: 0,
    },
  ],
  'style/no-tabs': 'error',
  'style/no-trailing-spaces': 'error',
  'style/no-whitespace-before-property': 'error',
  'style/object-curly-spacing': [
    'error',
    'always',
  ],
  'style/operator-linebreak': [
    'error',
    'before',
  ],
  'style/padded-blocks': [
    'error',
    {
      blocks: 'never',
      classes: 'never',
      switches: 'never',
    },
  ],
  'style/quote-props': [
    'error',
    'as-needed',
  ],
  'style/quotes': [
    'error',
    'single',
    {
      avoidEscape: true,
      allowTemplateLiterals: 'always',
    },
  ],
  'style/rest-spread-spacing': [
    'error',
    'never',
  ],
  'style/semi': [
    'error',
    'always',
  ],
  'style/semi-spacing': [
    'error',
    {
      after: true,
      before: false,
    },
  ],
  'style/space-before-blocks': [
    'error',
    'always',
  ],
  'style/space-before-function-paren': [
    'error',
    {
      anonymous: 'always',
      asyncArrow: 'always',
      named: 'never',
    },
  ],
  'style/space-in-parens': [
    'error',
    'never',
  ],
  'style/space-infix-ops': 'error',
  'style/space-unary-ops': [
    'error',
    {
      nonwords: false,
      words: true,
    },
  ],
  'style/spaced-comment': [
    'error',
    'always',
    {
      block: {
        balanced: true,
        exceptions: [
          '*',
        ],
        markers: [
          '!',
        ],
      },
      line: {
        exceptions: [
          '/',
          '#',
        ],
        markers: [
          '/',
        ],
      },
    },
  ],
  'style/template-curly-spacing': 'error',
  'style/template-tag-spacing': [
    'error',
    'never',
  ],
  'style/type-annotation-spacing': [
    'error',
    {},
  ],
  'style/type-generic-spacing': 'error',
  'style/type-named-tuple-spacing': 'error',
  'style/wrap-iife': [
    'error',
    'any',
    {
      functionPrototypeMethods: true,
    },
  ],
  'style/yield-star-spacing': [
    'error',
    {
      after: true,
      before: false,
    },
  ],
  'style/jsx-closing-bracket-location': 'error',
  'style/jsx-closing-tag-location': 'error',
  'style/jsx-curly-brace-presence': [
    'error',
    {
      propElementValues: 'always',
    },
  ],
  'style/jsx-curly-newline': 'error',
  'style/jsx-curly-spacing': [
    'error',
    'never',
  ],
  'style/jsx-equals-spacing': 'error',
  'style/jsx-first-prop-new-line': 'error',
  'style/jsx-function-call-newline': [
    'error',
    'multiline',
  ],
  'style/jsx-indent-props': [
    'error',
    2,
  ],
  'style/jsx-max-props-per-line': [
    'error',
    {
      maximum: 1,
      when: 'multiline',
    },
  ],
  'style/jsx-one-expression-per-line': [
    'error',
    {
      allow: 'single-child',
    },
  ],
  'style/jsx-quotes': [
    'error',
    'prefer-double',
  ],
  'style/jsx-tag-spacing': [
    'error',
    {
      afterOpening: 'never',
      beforeClosing: 'never',
      beforeSelfClosing: 'always',
      closingSlash: 'never',
    },
  ],
  'style/jsx-wrap-multilines': [
    'error',
    {
      arrow: 'parens-new-line',
      assignment: 'parens-new-line',
      condition: 'parens-new-line',
      declaration: 'parens-new-line',
      logical: 'parens-new-line',
      prop: 'parens-new-line',
      propertyValue: 'parens-new-line',
      return: 'parens-new-line',
    },
  ],
  'style/linebreak-style': [
    'error',
    'unix',
  ],
  'import/no-absolute-path': 'error',
  'import/no-self-import': 'error',
  'import/no-cycle': 'error',
  'import/no-duplicates': [
    'error',
    {
      preferInline: false,
    },
  ],
  'import/first': 'error',
  'import/newline-after-import': 'error',
  'node/handle-callback-err': 'error',
  'node/no-exports-assign': 'error',
  'node/no-new-require': 'error',
  'node/no-path-concat': 'error',
  'unicorn/filename-case': [
    'error',
    {
      case: 'kebabCase',
    },
  ],
  'unicorn/error-message': 'error',
  'unicorn/new-for-builtins': 'error',
  'unicorn/no-abusive-eslint-disable': 'error',
  'unicorn/no-array-callback-reference': 'error',
  'unicorn/no-invalid-fetch-options': 'error',
  'unicorn/no-invalid-remove-event-listener': 'error',
  'unicorn/no-new-array': 'error',
  'unicorn/no-static-only-class': 'error',
  'unicorn/no-single-promise-in-promise-methods': 'error',
  'unicorn/no-unnecessary-await': 'error',
  'unicorn/no-useless-fallback-in-spread': 'error',
  'unicorn/no-useless-promise-resolve-reject': 'error',
  'unicorn/no-useless-spread': 'error',
  'unicorn/prefer-array-find': 'error',
  'unicorn/prefer-array-flat': 'error',
  'unicorn/prefer-array-flat-map': 'error',
  'unicorn/prefer-array-index-of': 'error',
  'unicorn/prefer-array-some': 'error',
  'unicorn/prefer-at': 'error',
  'unicorn/prefer-date-now': 'error',
  'unicorn/prefer-default-parameters': 'error',
  'unicorn/prefer-includes': 'error',
  'unicorn/prefer-negative-index': 'error',
  'unicorn/prefer-number-properties': 'error',
  'unicorn/prefer-object-from-entries': 'error',
  'unicorn/prefer-set-has': 'error',
  'unicorn/prefer-string-starts-ends-with': 'error',
  'unicorn/prefer-string-trim-start-end': 'error',
  'unicorn/prefer-type-error': 'error',
  'unicorn/throw-new-error': 'error',
} satisfies NonNullable<OxlintConfig['rules']>;

export const syntaxRules = {
  'policy/no-dupe-args': 'off',
  'policy/no-restricted-syntax': [
    'error',
    {
      selector: 'TSEnumDeclaration',
      message: 'Use a union or const object instead of an enum.',
    },
  ],
  'eslint/constructor-super': 'off',
  'eslint/getter-return': 'off',
  'eslint/no-class-assign': 'off',
  'eslint/no-const-assign': 'off',
  'eslint/no-dupe-class-members': 'off',
  'eslint/no-new-native-nonconstructor': 'off',
  'eslint/no-obj-calls': 'off',
  'eslint/no-redeclare': 'error',
  'eslint/no-setter-return': 'off',
  'eslint/no-shadow': 'error',
  'eslint/no-this-before-super': 'off',
  'eslint/no-undef': 'off',
  'eslint/no-unreachable': 'off',
  'eslint/no-unsafe-negation': 'off',
  'eslint/no-unused-vars': [
    'error',
    {
      args: 'all',
      argsIgnorePattern: '^_',
      caughtErrors: 'all',
      caughtErrorsIgnorePattern: '^_',
      varsIgnorePattern: '^_',
      ignoreRestSiblings: true,
    },
  ],
  'eslint/no-unused-expressions': 'error',
  'eslint/no-use-before-define': [
    'error',
    {
      functions: false,
      typedefs: false,
    },
  ],
  'eslint/no-empty-function': 'error',
  'unicorn/no-static-only-class': 'off',
  'typescript/adjacent-overload-signatures': 'error',
  'typescript/array-type': [
    'error',
    {
      default: 'array-simple',
    },
  ],
  'typescript/ban-ts-comment': [
    'error',
    {
      'ts-ignore': true,
      'ts-nocheck': true,
      'ts-check': false,
      'ts-expect-error': 'allow-with-description',
      minimumDescriptionLength: 3,
    },
  ],
  'typescript/class-literal-property-style': [
    'error',
    'fields',
  ],
  'typescript/consistent-generic-constructors': [
    'error',
    'constructor',
  ],
  'typescript/consistent-indexed-object-style': [
    'error',
    'record',
  ],
  'typescript/consistent-type-assertions': [
    'error',
    {
      assertionStyle: 'as',
      objectLiteralTypeAssertions: 'never',
      arrayLiteralTypeAssertions: 'never',
    },
  ],
  'typescript/consistent-type-definitions': [
    'error',
    'type',
  ],
  'typescript/consistent-type-imports': [
    'error',
    {
      prefer: 'type-imports',
      fixStyle: 'separate-type-imports',
    },
  ],
  'typescript/explicit-module-boundary-types': [
    'error',
    {
      allowHigherOrderFunctions: false,
      allowDirectConstAssertionInArrowFunctions: false,
      allowTypedFunctionExpressions: true,
    },
  ],
  'typescript/method-signature-style': [
    'error',
    'property',
  ],
  'eslint/id-match': [
    'error',
    '^_?(?:[a-z][a-zA-Z0-9]*|[A-Z][a-zA-Z0-9]*|[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*)$',
    {
      onlyDeclarations: true,
      properties: false,
      ignoreDestructuring: true,
    },
  ],
  'typescript/no-confusing-non-null-assertion': 'error',
  'typescript/no-dynamic-delete': 'error',
  'typescript/no-empty-object-type': 'error',
  'typescript/no-explicit-any': 'error',
  'typescript/no-extra-non-null-assertion': 'error',
  'typescript/no-extraneous-class': 'error',
  'typescript/no-inferrable-types': 'error',
  'typescript/no-invalid-void-type': 'error',
  'typescript/no-misused-new': 'error',
  'typescript/no-namespace': 'error',
  'typescript/no-non-null-asserted-nullish-coalescing': 'error',
  'typescript/no-non-null-asserted-optional-chain': 'error',
  'typescript/no-non-null-assertion': 'error',
  'typescript/no-unnecessary-type-constraint': 'error',
  'typescript/prefer-as-const': 'error',
  'typescript/prefer-for-of': 'error',
  'typescript/prefer-function-type': 'error',
  'typescript/prefer-literal-enum-member': 'error',
  'typescript/triple-slash-reference': 'error',
  'import/consistent-type-specifier-style': [
    'error',
    'prefer-top-level',
  ],
} satisfies NonNullable<OxlintConfig['rules']>;

export const typedRules = {
  'eslint/no-throw-literal': 'off',
  'eslint/prefer-promise-reject-errors': 'off',
  'typescript/await-thenable': 'error',
  'typescript/consistent-type-exports': 'error',
  'typescript/no-array-delete': 'error',
  'typescript/no-base-to-string': 'error',
  'typescript/no-confusing-void-expression': 'error',
  'typescript/no-deprecated': 'error',
  'typescript/no-duplicate-type-constituents': 'error',
  'typescript/no-floating-promises': [
    'error',
    {
      ignoreVoid: false,
      ignoreIIFE: false,
      checkThenables: true,
    },
  ],
  'typescript/no-for-in-array': 'error',
  'typescript/no-implied-eval': 'error',
  'typescript/no-meaningless-void-operator': 'error',
  'typescript/no-misused-promises': [
    'error',
    {
      checksConditionals: true,
      checksSpreads: true,
      checksVoidReturn: true,
    },
  ],
  'typescript/no-misused-spread': 'error',
  'typescript/no-mixed-enums': 'error',
  'typescript/no-redundant-type-constituents': 'error',
  'typescript/no-unnecessary-boolean-literal-compare': 'error',
  'typescript/no-unnecessary-condition': [
    'error',
    {
      checkTypePredicates: false,
    },
  ],
  'typescript/no-unnecessary-template-expression': 'error',
  'typescript/no-unnecessary-type-arguments': 'error',
  'typescript/no-unnecessary-type-assertion': 'error',
  'typescript/no-unnecessary-type-conversion': 'error',
  'typescript/no-unsafe-argument': 'error',
  'typescript/no-unsafe-assignment': 'error',
  'typescript/no-unsafe-call': 'error',
  'typescript/no-unsafe-enum-comparison': 'error',
  'typescript/no-unsafe-member-access': 'error',
  'typescript/no-unsafe-return': 'error',
  'typescript/no-unsafe-type-assertion': 'error',
  'typescript/no-unsafe-unary-minus': 'error',
  'typescript/only-throw-error': [
    'error',
    {
      allowThrowingAny: false,
      allowThrowingUnknown: false,
      allowRethrowing: true,
    },
  ],
  'typescript/prefer-find': 'error',
  'typescript/prefer-includes': 'error',
  'typescript/prefer-nullish-coalescing': 'error',
  'typescript/prefer-optional-chain': 'error',
  'typescript/prefer-readonly': 'error',
  'typescript/prefer-reduce-type-parameter': 'error',
  'typescript/prefer-regexp-exec': 'error',
  'typescript/prefer-string-starts-ends-with': 'error',
  'typescript/promise-function-async': 'error',
  'typescript/require-array-sort-compare': 'error',
  'typescript/require-await': 'error',
  'typescript/restrict-plus-operands': [
    'error',
    {
      allowAny: false,
      allowBoolean: false,
      allowNullish: false,
      allowNumberAndString: false,
      allowRegExp: false,
    },
  ],
  'typescript/restrict-template-expressions': [
    'error',
    {
      allowAny: false,
      allowBoolean: false,
      allowNullish: false,
      allowNumber: false,
      allowRegExp: false,
      allowNever: false,
    },
  ],
  'typescript/return-await': [
    'error',
    'always',
  ],
  'typescript/strict-boolean-expressions': [
    'error',
    {
      allowString: false,
      allowNumber: false,
      allowNullableObject: true,
      allowNullableBoolean: false,
      allowNullableString: false,
      allowNullableNumber: false,
      allowNullableEnum: false,
      allowAny: false,
    },
  ],
  'typescript/switch-exhaustiveness-check': 'error',
  'typescript/unbound-method': 'error',
  'typescript/use-unknown-in-catch-callback-variable': 'error',
  'unicorn/prefer-array-find': 'off',
  'unicorn/prefer-includes': 'off',
  'unicorn/prefer-string-starts-ends-with': 'off',
} satisfies NonNullable<OxlintConfig['rules']>;

export const declarationRules = {
  'policy/no-dupe-args': 'off',
  'policy/no-octal': 'off',
  'policy/no-deprecated-api': 'off',
  'policy/node-builtins': 'off',
  'policy/es-builtins': 'off',
  'policy/no-process-exit': 'off',
  'policy/prefer-node-protocol': 'off',
  'policy/no-unnecessary-polyfills': 'off',
  'policy/no-restricted-syntax': 'off',
  'eslint/constructor-super': 'off',
  'eslint/for-direction': 'off',
  'eslint/getter-return': 'off',
  'eslint/no-async-promise-executor': 'off',
  'eslint/no-await-in-loop': 'off',
  'eslint/no-case-declarations': 'off',
  'eslint/no-class-assign': 'off',
  'eslint/no-compare-neg-zero': 'off',
  'eslint/no-cond-assign': 'off',
  'eslint/no-const-assign': 'off',
  'eslint/no-constant-binary-expression': 'off',
  'eslint/no-constant-condition': 'off',
  'eslint/no-control-regex': 'off',
  'eslint/no-debugger': 'off',
  'eslint/no-delete-var': 'off',
  'eslint/no-dupe-class-members': 'off',
  'eslint/no-dupe-else-if': 'off',
  'eslint/no-dupe-keys': 'off',
  'eslint/no-duplicate-case': 'off',
  'eslint/no-empty': 'off',
  'eslint/no-empty-character-class': 'off',
  'eslint/no-empty-function': 'off',
  'eslint/no-empty-pattern': 'off',
  'eslint/no-empty-static-block': 'off',
  'eslint/no-eval': 'off',
  'eslint/no-ex-assign': 'off',
  'eslint/no-fallthrough': 'off',
  'eslint/no-global-assign': 'off',
  'eslint/no-implicit-coercion': 'off',
  'eslint/no-import-assign': 'off',
  'eslint/no-inner-declarations': 'off',
  'eslint/no-invalid-regexp': 'off',
  'eslint/no-irregular-whitespace': 'off',
  'eslint/no-loss-of-precision': 'off',
  'eslint/no-misleading-character-class': 'off',
  'eslint/no-new-native-nonconstructor': 'off',
  'eslint/no-new-wrappers': 'off',
  'eslint/no-nonoctal-decimal-escape': 'off',
  'eslint/no-obj-calls': 'off',
  'eslint/no-promise-executor-return': 'off',
  'eslint/no-prototype-builtins': 'off',
  'eslint/no-redeclare': 'off',
  'eslint/no-regex-spaces': 'off',
  'eslint/no-self-assign': 'off',
  'eslint/no-self-compare': 'off',
  'eslint/no-setter-return': 'off',
  'eslint/no-shadow': 'off',
  'eslint/no-shadow-restricted-names': 'off',
  'eslint/no-sparse-arrays': 'off',
  'eslint/no-template-curly-in-string': 'off',
  'eslint/no-this-before-super': 'off',
  'eslint/no-throw-literal': 'off',
  'eslint/no-undef': 'off',
  'eslint/no-unexpected-multiline': 'off',
  'eslint/no-unreachable': 'off',
  'eslint/no-unreachable-loop': 'off',
  'eslint/no-unsafe-finally': 'off',
  'eslint/no-unsafe-negation': 'off',
  'eslint/no-unsafe-optional-chaining': 'off',
  'eslint/no-unused-expressions': 'off',
  'eslint/no-unused-labels': 'off',
  'eslint/no-unused-private-class-members': 'off',
  'eslint/no-unused-vars': 'off',
  'eslint/no-use-before-define': 'off',
  'eslint/no-useless-backreference': 'off',
  'eslint/no-useless-catch': 'off',
  'eslint/no-useless-escape': 'off',
  'eslint/no-var': 'off',
  'eslint/no-with': 'off',
  'eslint/object-shorthand': 'off',
  'eslint/prefer-const': 'off',
  'eslint/prefer-object-spread': 'off',
  'eslint/prefer-promise-reject-errors': 'off',
  'eslint/prefer-rest-params': 'off',
  'eslint/prefer-spread': 'off',
  'eslint/require-yield': 'off',
  'eslint/use-isnan': 'off',
  'eslint/valid-typeof': 'off',
  'eslint/curly': 'off',
  'eslint/eqeqeq': 'off',
  'eslint/complexity': 'off',
  'eslint/max-depth': 'off',
  'eslint/max-params': 'off',
  'node/handle-callback-err': 'off',
  'node/no-exports-assign': 'off',
  'node/no-new-require': 'off',
  'node/no-path-concat': 'off',
  'unicorn/filename-case': 'off',
  'unicorn/error-message': 'off',
  'unicorn/new-for-builtins': 'off',
  'unicorn/no-array-callback-reference': 'off',
  'unicorn/no-invalid-fetch-options': 'off',
  'unicorn/no-invalid-remove-event-listener': 'off',
  'unicorn/no-new-array': 'off',
  'unicorn/no-static-only-class': 'off',
  'unicorn/no-single-promise-in-promise-methods': 'off',
  'unicorn/no-unnecessary-await': 'off',
  'unicorn/no-useless-fallback-in-spread': 'off',
  'unicorn/no-useless-promise-resolve-reject': 'off',
  'unicorn/no-useless-spread': 'off',
  'unicorn/prefer-array-find': 'off',
  'unicorn/prefer-array-flat': 'off',
  'unicorn/prefer-array-flat-map': 'off',
  'unicorn/prefer-array-index-of': 'off',
  'unicorn/prefer-array-some': 'off',
  'unicorn/prefer-at': 'off',
  'unicorn/prefer-date-now': 'off',
  'unicorn/prefer-default-parameters': 'off',
  'unicorn/prefer-includes': 'off',
  'unicorn/prefer-negative-index': 'off',
  'unicorn/prefer-number-properties': 'off',
  'unicorn/prefer-object-from-entries': 'off',
  'unicorn/prefer-set-has': 'off',
  'unicorn/prefer-string-starts-ends-with': 'off',
  'unicorn/prefer-string-trim-start-end': 'off',
  'unicorn/prefer-type-error': 'off',
  'unicorn/throw-new-error': 'off',
  'typescript/consistent-type-definitions': 'off',
  'typescript/explicit-module-boundary-types': 'off',
  'typescript/no-namespace': 'off',
  'typescript/no-extraneous-class': 'off',
  'typescript/no-empty-object-type': [
    'error',
    {
      allowInterfaces: 'always',
    },
  ],
  'typescript/method-signature-style': 'off',
} satisfies NonNullable<OxlintConfig['rules']>;

export const testRules = {
  'eslint/complexity': 'off',
  'eslint/max-depth': 'off',
  'eslint/max-params': 'off',
  'unicorn/filename-case': 'off',
  'typescript/explicit-module-boundary-types': 'off',
  'typescript/no-non-null-assertion': 'off',
  'typescript/no-explicit-any': 'off',
  'typescript/no-unsafe-type-assertion': 'off',
  'typescript/no-unsafe-argument': 'off',
  'typescript/no-unsafe-assignment': 'off',
  'typescript/no-unsafe-call': 'off',
  'typescript/no-unsafe-member-access': 'off',
  'typescript/no-unsafe-return': 'off',
  'typescript/consistent-type-assertions': 'off',
} satisfies NonNullable<OxlintConfig['rules']>;
